### ISSUE TITLE
19.10 worked for eGPU but then fails on internal

### ISSUE THREAD

**Issue by jasoncorso** [hertg/egpu-switcher#28]
Thanks for the great tool.  I was easily able to get it working on 19.10 (with NVIDIA 440 drivers).  It directly works for the external GPU, but after a reboot without the eGPU connected, it fails.  The error message upon `cleanup` said something about no backup `xorg.conf` file.  I haven't configured X11 myself in a decade, so this surprised me.  I wonder if you have any thoughts about what's going on here or how to overcome it.  (I did select to explicitly set the internal GPU even though the default was `N`.)
Thanks

**Comment by hertg** [comment]
Glad to hear that the setup worked.

1. **Backup not found, restoring system without xorg.conf**
The `Backup not found, restoring system without xorg.conf` message is more of an informational output rather than an error. 
The background for this is that the egpu-switcher will create a new `xorg.conf` file and backup the one you had before (So you don't lose your manual X11 configuration, if you had one). When running the cleanup command, the `xorg.conf` created by egpu-switcher is being removed and your previous configuration restored. 
The message only tells you that there is no backup of a previous configuration, which makes sense in your case, as you didn't configure X11 yourself.
2. **Explicitly setting the internal GPU** 
This is kind of an experimental feature for people with a hybrid GPU setup in their computer (CPU integrated graphics + a discrete GPU). You'd only need to set this if you somehow want to prevent X11 from using one of them. There have been some reports that setting it explicitly wouldn't work properly, where i can't do much about it, unfortunately. 
It's usually better to let X11 figure it out themselves which GPU to use in a hybrid setup. That's why i introduced the default `n` option. It would probably be a good idea for me to mention that it's experimental, because it's not that clear right now.

**Comment by jasoncorso** [comment]
Thnks, the challenge that I am facing is that I need to `setup` the switcher when I want to use the eGPU and then `cleanup` the switcher when I want to not use the eGPU.  This basically means rather than only a reboot, I need to do these extra steps each time, which is annoying.  Do I need to set up an xorg.conf for my internal GPU first to overcome this issue?

**Comment by hertg** [comment]
I assume that you have your eGPU disconnected when you want to use the internal GPU. Because the script will always prefer the eGPU on startup, if the eGPU is connected to your computer.

Maybe there is an issue where the egpu-switcher systemd service doesn't execute on startup. You could check that by taking a look at the logs with `journalctl`. The systemd service basically just executes the `egpu-switcher switch auto` command before your display-manager gets started.

You could also try to manually execute `sudo egpu-switcher switch internal` before rebooting and disconnecting your eGPU.
