### ISSUE TITLE
Don't specify driver "intel" for Ubuntu 20.04.

### ISSUE THREAD

**Issue by rvanlaar** [hertg/egpu-switcher#33]
Ubuntu 20.04 has multiple problems with the intel driver:

https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1867668
https://bugs.launchpad.net/ubuntu/+bug/1875162
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2845#note_478292

My solution:
have an empty xorg.conf.internal file.

**Comment by hertg** [comment]
I don't think the egpu-switcher script should contain exceptional code for certain versions of distributions. If there happens to be an issue in a certain distro/version, it's up to the maintainers of the distro to fix it. Introducing workarounds in egpu-switcher would unnecessarily complicate the script, and would require continuous checks on if the workarounds are still needed.

Apart from that, the current defaults are that the internal GPU is not specified explicitly. Therefore the issue does only arise if someone explicitly specified their internal GPU to be the Intel Integrated Graphics. Users not specifying the internal GPU will get an empty `xorg.conf.internal` and should therefore already be safe.

But thanks for the feedback. It would probably be nice to have a "Known Issues" section in the README or create a page in the Wiki. I just created a new `knowledge` label and applied it to this issue so it doesn't get lost if I create such a page in the future.

**Comment by rvanlaar** [comment]
It's not much fun to maintain specific config for different distro versions.
How come the egpu-switcher setup and config produce different results?
Why does it create a specific xorg file when it's not needed?

To put it bluntly. The egpu switcher config is broken on ubuntu 20.04.
When the external nvidia card is not in use, it will not work.

**Comment by hertg** [comment]
> How come the egpu-switcher setup and config produce different results?

I am guessing you are referring to the commands `setup` and `config`. I'll try to explain the difference :)

Originally those two commands were just a single `setup` command. I've separated those because of the issue #5. Basically, the egpu-switcher gets uninstalled and then reinstalled everytime the user updates to a new version, meaning the generated `xorg.conf.*` files get deleted. This posed the problem that the user needed to re-run the `setup` everytime he updated the egpu-switcher because their configs (selection of the GPUs) were lost.

The `egpu-switcher config` command prompts the user to select their external GPU and lets the user optionally select a dedicated internal GPU. These configurations will be saved in `/etc/egpu-switcher/egpu-switcher.conf`. Here's an example of my current config:

![image](https://user-images.githubusercontent.com/3533648/80705627-0c7fc500-8ae7-11ea-8c97-8e21bd61adba.png)

As you can see, i do not have a specific internal GPU selected.

The `egpu-switcher setup` command first checks if there is an existing configuration. If not, it will call the `egpu-switcher config` command internally (unless you provided the `--noprompt` parameter). Additionally to that, it will then create the `xorg.conf.*` files depending on the configuration file, execute the `egpu-switcher switch auto` command internally and create/enable the egpu-switcher systemd service.

> Why does it create a specific xorg file when it's not needed?

To fix this issue, i'd recommend you to re-run the config command and don't select a specific internal GPU.

The easiest way to achieve this is to execute the `egpu-switcher cleanup` command and then re-run the setup.

```sh
# this purges the generated xorg.conf.* files 
# and removes your /etc/egpu-switcher/egpu-switcher.conf.
sudo egpu-switcher cleanup --hard

# Re-run the setup
sudo egpu-switcher setup
```

**Comment by rvanlaar** [comment]
I've followed the commands and selected 'N' when I was asked to specify an internal gpu.
Could this be documented in the README? That it's not necessary to specify the internal gpu.

Now the `xorg.conf.internal` is empty, as it should be.

Thank you for this explanation.
