### ISSUE TITLE
"switch egpu" does not create symlink to "xorg.conf.egpu".

### ISSUE THREAD

**Issue by tominglis** [hertg/egpu-switcher#38]
**Context:**

I have a clean install of Ubuntu 20.04 on my Lenovo ThinkPad T480, with Intel UHD Graphics 620 and the latest UEFI updates.

I have an Akitio Node eGPU chassis with a Sapphire Radeon R9 Nano GPU.

I have an Iiyama G-Master GB2488HSU monitor connected to the laptop via HDMI and the eGPU via DisplayPort.

**Problem:**

When I run "sudo egpu-switcher switch egpu", it does not attempt to create the required symlink between xorg.conf.egpu and xorg.conf.

Conversely, when I run "sudo egpu-switcher switch internal" the required symlink between xorg.conf.internal (which is blank) and xorg.conf is created.

If I manually create the symlink then the eGPU is loaded as the main display device as expected on reboot.

I have tried "sudo egpu-switcher cleanup --hard" followed by "sudo egpu-switcher setup".

I have also tried "sudo egpu-switcher cleanup --hard" followed by "sudo apt purge egpu-switcher", "sudo apt install egpu-switcher" and "sudo egpu-switcher setup".

For each setup step I have selected N when asked if I want to define an internal GPU (answering Y previously caused issues with my Intel GPU but did allow the symlinking to occur).

**Evidence:**

After running the "sudo egpu-switcher switch egpu" command, there is either no symlink in /etc/X11/ or a symlink to the xorg.conf.internal file.

**Comment by hertg** [comment]
Hi @tominglis 

I've seen that you own an AMD GPU, so this issue might be related to #34.
This issue was fixed via PR, but I wasn't able to create a release yet.

Would it be possible for you to do the following steps and post the results?
1. Install and setup egpu-switcher
1. Edit the `/usr/bin/egpu-switcher` file (with sudo) and uncomment the following line (nearly at the top)
   ```
   set -o xtrace # debug
   ```
1. Run `sudo egpu-switcher switch egpu`
1. Post the output here

If the script also stops at the line
```
+ disp_disconnect=0
```

It's probably the same issue :)

**Comment by tominglis** [comment]
I tried this and the script stopped at that point, so it does seem to be this issue.

I'm looking forward to the release! :-)

In the meantime perhaps I could try replacing the loop suggested in the other issue?

**Comment by hertg** [comment]
I've created the release 0.14.0 which includes this fix.
You should be able to update now :)
