### ISSUE TITLE
Need to reboot twice in order to change de GPU

### ISSUE THREAD

**Issue by nightelf7** [hertg/egpu-switcher#45]
I have a Linux Mint 20 with the default kernel 5.4.0-40-generic.
I have an intel uhd 620 and a AMD RADEON 5700XT with the eGPU box Razer Core X.
I have configured egpu-switcher with the default option.
When I am with the eGPU and reboot without it the Linux stop booting I just see a cursos blinking.
If I reboot again the intel 620UHD is properly detected.
From the intel 620uhd I reboot with the eGPU plugged it the performance is not good with same lagging in the movements.
But if I reboot again the eGPU is working fine.
Thank you for your support.

**Comment by hertg** [comment]
Did you install `egpu-switcher` via the ppa or directly via git?

Please check the contents of your `egpu.service` file with the following command:
```sh
sudo cat /usr/share/egpu-switcher/egpu.service
```

If you do not see the following line in there, try adding it in the `[Unit]` section.
```sh
Before=display-manager.service
```

So that the whole file looks like this:
```sh
[Unit]
Description=EGPU Service

[Service]
Type=oneshot
ExecStart=/usr/bin/egpu-switcher switch auto

[Install]
WantedBy=multi-user.target
```

As a last step, reload the systemctl services with `sudo systemctl daemon-reload` and restart your computer.
Does that resolve the issue?

**Comment by nightelf7** [comment]
I installed by ppa.
I changed what you told me and the behaviour is the same.
Now my file looks like this:
sudo cat /usr/share/egpu-switcher/egpu.service

[Unit]
Description=EGPU Service
Before=display-manager.service

[Service]
Type=oneshot
ExecStart=/usr/bin/egpu-switcher switch auto

[Install]
WantedBy=multi-user.target

**Comment by hertg** [comment]
Can you please check if a reboot is necessary, or if restarting the display-manager is already enough?
Instead of rebooting the machine, try changing to another tty (ie. <kbd>CTRL</kbd>+ <kbd>ALT</kbd> + <kbd>F2</kbd> for tty2) and restart the display manager with `sudo systemctl restart display-manager`.

If that is already enough, there seems to be a timing issue with egpu-switcher, meaning it doesn't necessarily run egpu-switcher before the display-manager starts. Which is weird, because my proposed change to the `egpu.service` above should handle that.

If restarting the display-manager is not enough, there might be another problem that is not directly related to egpu-switcher.

**Comment by nightelf7** [comment]
Unfortunately when I change the first time to AMD RADEON the system is not responding any key stroke I have to power off with the button. I will try with the change from RADEON to Intel.

**Comment by hertg** [comment]
So it's not even recognizing keystrokes from the laptop keyboard? That seems strange.
I'm not really sure what could be the problem there. You could try changing your Thunderbolt Security configurations in your BIOS and see if that makes any difference.

I did set my Thunderbolt Security to `No Security`, as I was also experiencing issues with the other options. 

> *Please be aware that this might make you vulnerable to some physical attacks via Thunderbolt (ie. https://thunderclap.io/). But if your hard drive is encrypted and you don't usually leave your device running unsupervised, the actual risk should be very limited as it requires physical presence of an attacker.*

**Comment by nightelf7** [comment]
For intel your workaround in the /usr/share/egpu-switcher/egpu.service it works.
I have to test it with the change from intel to eGPU several times in order to say if everything is working fine.
Thank you very much for your help.

**Comment by hertg** [comment]
@nightelf7 
I released a new version some days ago, where i've made changes to the systemd service.
You could try updating to the latest version of egpu-switcher and have a look if it resolves your issue.

**Comment by nightelf7** [comment]
Now it works fine without any second reboot.
Thanks!
