### ISSUE TITLE
xorg.conf.internal is empty!

### ISSUE THREAD

**Issue by Sandvich** [hertg/egpu-switcher#61]
Hi, I'm having the same issue as #55:

```
❯ sudo egpu-switcher switch auto
[info] Automatically detecting if egpu is connected... 
/usr/bin/egpu-switcher: line 138: busArray[0]: unbound variable
```

As mentioned in that issue, I don't have a BusID in my active xorg.conf. But that's because, for some reason, I don't have _anything_ in my xorg.conf! I'm not familiar with these files, so I'm not sure what I should expect the file to contain.

The external looks normal:
```
❯ cat xorg.conf.egpu
Section "Module"
    Load           "modesetting"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "amdgpu"
    BusID          "48:00.0"
    Option         "AllowEmptyInitialConfiguration"
    Option         "AllowExternalGpus" "True"
EndSection
```
But the internal is just empty. It exists, but has no contents. Any ideas what could have happened?

**Comment by ewagner12** [comment]
It's the expected behavior to have an empty xorg.conf.internal if you selected "N" to the prompt:
<pre>Would you like to define a specific<font color="#26A269"><b> INTERNAL</b></font> GPU? (not recommended) [y/N]:</pre>
An empty xorg.conf lets your distro automatically configure everything, which usually works best for most (but not all) people's setups
I would make sure that you've run the commands:
```
sudo egpu-switcher config
sudo egpu-switcher setup
```
and that they've completed without errors. If you still are getting the error, maybe check the path of the xorg.conf files. They are expected to be in /etc/X11

**Comment by Sandvich** [comment]
Ah, okay. I'm not sure what's going on then - it seems to be functioning correctly but only if I don't try to switch when the system is booted - IE just leave it on auto.
This may be a deeper issue related to my specific system, idk. I have some weird issues even when the GPU is set up correctly...

**Comment by Sandvich** [comment]
It seems to be working again randomly? But also, I'm trying to get wayland working instead because fedora people seem to prefer wayland :shrug: 
So I'll close this for now.

**Comment by hertg** [comment]
Sorry for the late response.

As ewagner12 pointed out, it's expected behavior to have an empty internal configuration if you left it at the default settings during setup.

> Ah, okay. I'm not sure what's going on then - it seems to be functioning correctly but only if I don't try to switch when the system is booted

I assume you are aware that "switching" after boot also requires restarting your display-manager with `systemctl restart display-manager`? (This will kill your Xsession and therefore kill all user applications you've started) 
On the next bootup, it will run `egpu-switcher switch auto` again automatically, so if you switched manually on the previous boot, it is overwritten again as long as `egpu.service` is enabled in systemd.

@ewagner12 btw. thanks a lot for jumping in and answering issues, I appreciate it a lot :)

**Comment by Sandvich** [comment]
Makes sense. I was booting into runlevel 3, so no GUI until I manually switched it, but I'm now just trying the wayland method instead. I'm just having all kinds of strange bugs with the enclosure, and it must be that I'm doing something wrong...
