### ISSUE TITLE
/usr/bin/egpu-switcher: line 116: 16#0:: syntax error in expression (error token is ":")

### ISSUE THREAD

**Issue by krikey** [hertg/egpu-switcher#70]
I used the instructions at https://github.com/hertg/egpu-switcher#installation to set up the repo and install the software, however when running:

`sudo egpu-switcher setup`

I get the following error

`/usr/bin/egpu-switcher: line 116: 16#0:: syntax error in expression (error token is ":")`

My laptop is an ASUS Tuf-Dash F15 running Pop!OS 21.05 with a Razer Core X eGPU and NVidia 1080Ti

**Comment by engelmeierpaul** [comment]
This issue was fixed #68 and is a duplicate of #59. I suppose you set it up the Ubuntu way, so you'll either have to wait until @hertg updates the ppa or you could set it up [the other way](https://github.com/hertg/egpu-switcher#installation). Let me know if you need assistance, I'd be happy to help. I think this issue can be closed.

**Comment by ivan-pinatti** [comment]
I just had this problem through the PPA installation and using the "manual" install worked.
Waiting for the new PPA release. :)
