### ISSUE TITLE
Firefox - hardware acceleration only works on legacy branch

### ISSUE THREAD

**Issue by Man-with-Arrow** [hertg/egpu-switcher#94]
Using Ubuntu 22.04 (default GNOME) with kernel version 5.15.0-52, Framework 11th Gen, RX 5700XT in Razer Core X. `egpu-switcher` built from source.

Building from `master`, Firefox isn't hardware accelerated. Browsing is slow, and video playback stutters. Completely uninstalling `egpu-switcher` and switching to `legacy` solves this.

Is this expected behaviour, as part of the rewrite?

**Comment by hertg** [comment]
That's not expected behaviour, no. Are you sure that the issue was only affecting hardware acceleration in Firefox, or did the newer egpu-switcher maybe not work at all without you realizing it? Just to make sure: Did you reconfigure egpu-switcher when using the latest version (if you updated from legacy, you need to reconfigure, because the config format changed). 

It's weird that the new version would behave differently if it actually ran as it should. One of the only X.org config differences between the legacy version and the new version is that the configuration file is put at `/etc/X11/xorg.conf.d/` now instead of directly into `/etc/X11/`.

If you have the time and motivation to troubleshoot that a bit for me, you could compare the contents of `/etc/X11/xorg.conf` when using the legacy version to the contents of `/etc/X11/xorg.conf.d/99-egpu-switcher.conf` when using the latest version.

**Comment by Man-with-Arrow** [comment]
Sure. I'll get to it during the weekend at the latest, hopefully before.

**Comment by Man-with-Arrow** [comment]
My apologies, due to an unrelated issue I switched over to Fedora 37 and Wayland. As your solution only works on X, I can't debug it...

**Comment by hertg** [comment]
@Man-with-Arrow np, thanks for getting back to me.
I'll leave the issue open as unconfirmed for now.

**Comment by Man-with-Arrow** [comment]
Moved back to X11. Glad to report that on fully-updated Fedora 37, the current branch works just fine! Since I was (maybe) the only user with the issue, I'm closing.
